# Generated by Django 2.2.2 on 2019-09-26 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0002_auto_20190926_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='situacao',
            field=models.IntegerField(choices=[(1, 'Cadastrado'), (2, 'Carona')], default=1),
        ),
    ]
