# Generated by Django 2.2.2 on 2020-02-13 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0003_auto_20190926_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='cod',
            field=models.IntegerField(default=0, max_length=5),
        ),
    ]
