# Generated by Django 2.2.2 on 2020-02-13 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0004_aluno_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='cod',
            field=models.CharField(default=0, max_length=8),
        ),
    ]
