# Generated by Django 2.2.2 on 2019-09-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('nome', models.CharField(max_length=100)),
                ('acao', models.IntegerField(choices=[(1, 'Ida'), (2, 'Ida e volta'), (3, 'Volta')], default=2)),
                ('instituicao', models.CharField(max_length=10)),
                ('situacao', models.CharField(max_length=10)),
            ],
        ),
    ]
