# Generated by Django 2.2.2 on 2019-09-26 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lista', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='data',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
